#!/bin/bash

clear

fun_bar () {

comando[0]="$1"

comando[1]="$2"

 (

[[ -e $HOME/fim ]] && rm $HOME/fim

${comando[0]} > /dev/null 2>&1

${comando[1]} > /dev/null 2>&1

touch $HOME/fim

 ) > /dev/null 2>&1 &

 tput civis

echo -ne "   \033[1;33mAGUARDE \033[1;37m- \033[1;33m["

while true; do

   for((i=0; i<18; i++)); do

   echo -ne "\033[1;31m#"

   sleep 0.1s

   done

   [[ -e $HOME/fim ]] && rm $HOME/fim && break

   echo -e "\033[1;33m]"

   sleep 1s

   tput cuu1

   tput dl1

   echo -ne "   \033[1;33mAGUARDE \033[1;37m- \033[1;33m["

done

echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"

tput cnorm

}

echo " "

fun_atts () {

  [[ -e /home/version ]] && rm /home/version

  [[ -e /tmp/att ]] && rm /tmp/att

	wget -q https://raw.githubusercontent.com/josecarlosmeza/linux/main/Subir%20a%20otro%20Servidor/version -O /home/version 2>/dev/null

	[[ -f "/home/version" ]] && mv /home/version /tmp/att

	[[ ! -e /bin/version ]] && rm -rf /bin/menu

} > /dev/null 2>&1

echo -e "                              \033[1;31mRedLibre\033[1;36m"

echo -e "   RedLibre" | figlet

echo " "

echo -e "   \033[1;32mVerificando actualizaciones disponibles\033[0m\n"

fun_bar 'fun_atts'

[[ ! -f "/tmp/att" ]] && {

	echo -e "\n\033[1;31m  Error al conectar con el servidor.\033[0m\n"

	echo -ne "\033[1;31m  ENTER \033[1;33mpara volver al \033[1;32mMENÚ\033[0m: "; read

	menu

}

echo " "

vrs1=$(sed -n '1 p' /bin/version | sed -e 's/[^0-9.]//ig')

vrs2=$(sed -n '1 p' /tmp/att | sed -e 's/[^0-9.]//ig')

[[ "$vrs1" == "$vrs2" ]] && {

  echo -e " \033[1;36m     El script ya está actualizado.\033[1;32m\n"

  rm /tmp/att > /dev/null 2>&1

  echo -e " \033[1;33m Más información: \033[1;37mRedLibre\n"

  echo -ne " \033[1;31m ENTER \033[1;33mpara volver al \033[1;32mMENÚ\033[0m: "; read

  menu

} || {

  echo -e "  \033[1;36m¡Hay una nueva actualización disponible!\033[1;33m\n"

  echo -e "  \033[1;33mMás información \033[1;31m(\033[1;36mRedLibre\033[1;31m): \033[1;37mRedLibre\n"

  echo -e "  \033[1;32mDetalles de la actualización:\033[0m\n"

  while read linha; do

    echo -e "  \033[1;37m- \033[1;33m$linha"

  done < "/tmp/att"

  echo " "

  echo -ne "  \033[1;32m¿Desea actualizar? \033[1;33m[s/n]:\033[1;37m "; read res

  if [[ "$res" = s || "$res" = S ]];then

    echo -e "\n\033[1;32m  Iniciando actualización...\033[0m"

    sleep 2

    wget -q https://raw.githubusercontent.com/josecarlosmeza/linux/main/Subir%20a%20otro%20Servidor/list -O /tmp/list 2>/dev/null

    [[ -f /tmp/list ]] && chmod +x /tmp/list && /tmp/list update /tmp /etc/RedLibre

    clear

    echo -e "\033[1;32m  Script actualizado correctamente.\033[0m\n"

    rm /tmp/att > /dev/null 2>&1

    echo -ne "\033[1;31m  ENTER \033[1;33mpara volver al \033[1;32mMENÚ\033[0m: "; read

    menu

  else

    menu

  fi

}

