#!/bin/bash
clear
echo -e "\033[1;32m¿Desea desinstalar RedLibre?\033[1;33m"
read -p "¿Eliminar? [s/n] " resp
if [[ "$resp" = s || "$resp" = S ]];then
    if command -v dnf &>/dev/null; then
      dnf remove -y screen nmap figlet squid squid3 dropbear httpd 2>/dev/null || true
    else
      apt-get purge -y screen nmap figlet squid squid3 dropbear apache2 2>/dev/null || true
    fi
    rm -f /bin/criarusuario /bin/expcleaner /bin/sshlimiter /bin/addhost /bin/listar /bin/sshmonitor /bin/ajuda /bin/menu /bin/userbackup /bin/tcpspeed /bin/badvpn /bin/otimizar /bin/speedtest /bin/trafego /bin/banner /bin/limit /bin/limite /bin/senharoot /bin/reiniciarservicos /bin/reiniciarsistema /bin/attscript /bin/criarteste /bin/socks  /bin/DropBear /bin/alterarlimite /bin/alterarsenha /bin/remover /bin/detalhes /bin/mudardata /bin/botssh /bin/infousers /bin/droplimiter /bin/conexao /bin/version > /dev/null 2>&1
    rm -rf /etc/RedLibre > /dev/null 2>&1
    clear
    echo -e "\033[1;36mObrigado por utilizar o RedLibre\033[1;33m"
    sleep 2
    cat /dev/null > ~/.bash_history && history -c && exit 0
else
    echo -e "\033[1;32mVolviendo al menú\033[1;33m"
    sleep 3
    menu
fi