#!/bin/bash

echo -e "\033[1;31m¡ATENCIÓN!\033[0m"
echo " "
echo -e "\033[1;33mEsta contraseña se usará para entrar al servidor.\033[0m"
echo -e "\033[1;32mEscriba la nueva contraseña para continuar...\033[1;31m\033[0m"
read  -p : pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
echo -e "\033[1;31m¡Contraseña cambiada correctamente!\033[0m"
sleep 5s
cd
clear

