#!/bin/bash
[[ -e /home/version ]] && rm -f /home/version
wget -q https://raw.githubusercontent.com/josecarlosmeza/linux/main/Subir%20a%20otro%20Servidor/version -O /home/version 2>/dev/null
[[ -f "/home/version" ]] && [[ -f "/bin/version" ]] && {
	vrs1=$(sed -n '1 p' /bin/version | sed -e 's/[^0-9.]//ig')
	vrs2=$(sed -n '1 p' /home/version | sed -e 's/[^0-9.]//ig')
	[[ "$vrs1" != "$vrs2" ]] && mv /home/version /tmp/att
}
rm -f /home/version 2>/dev/null
