#!/bin/bash
# Proxy Modificado y optimizado por RedLibre 


wget -O /usr/local/bin/wspy3 https://raw.githubusercontent.com/josecarlosmeza/linux/refs/heads/main/Subir%20a%20otro%20Servidor/wspy3-optV2
chmod +x /usr/local/bin/wspy3

# Installing Service
cat > /etc/systemd/system/wspy3.service << END
[Unit]
Description=Python Proxy Modificado por RedLibre 
Documentation=3794776469
After=network.target nss-lookup.target

[Service]
Type=simple
User=root
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/bin/python -O /usr/local/bin/wspy3
Restart=on-failure

[Install]
WantedBy=multi-user.target
END

systemctl enable wspy3.service
systemctl start wspy3.service
systemctl restart wspy3.service
